#!/bin/bash

iDIR="$HOME/.config/waybar/icons"

# Get Audio Volume
get_volume() {
    VOLUME=$(pamixer --get-volume)
}

# Get Mic Volume
get_mic_volume() {
    MICVOLUME=$(pamixer --default-source --get-volume)
}

# Get icons
get_icon() {
    get_volume
    if [[ "$VOLUME" -eq "0" ]]; then
        icon="$iDIR/volume-mute.png"
    elif [[ ("$VOLUME" -ge "0") && ("$VOLUME" -le "30") ]]; then
        icon="$iDIR/volume-low.png"
    elif [[ ("$VOLUME" -ge "30") && ("$VOLUME" -le "60") ]]; then
        icon="$iDIR/volume-mid.png"
    elif [[ ("$VOLUME" -ge "60") && ("$VOLUME" -le "100") ]]; then
        icon="$iDIR/volume-high.png"
    fi
}

# Notify
notify_user() {
    notify-send -h string:x-canonical-private-synchronous:sys-notify -u low -i "$icon" "Volume : $VOLUME %"
}

# Increase Volume
inc_volume() {
    pamixer -i 5 && get_icon && notify_user
}

# Decrease Volume
dec_volume() {
    pamixer -d 5 && get_icon && notify_user
}

# Toggle Mute
toggle_mute() {
    if [ "$(pamixer --get-mute)" == "false" ]; then
        pamixer -m && notify-send -h string:x-canonical-private-synchronous:sys-notify -u low -i "$iDIR/volume-mute.png" "Audio muted"
    elif [ "$(pamixer --get-mute)" == "true" ]; then
        get_icon
        pamixer -u && notify-send -h string:x-canonical-private-synchronous:sys-notify -u low -i "$icon" "Audio unmuted"
    fi
}

# Toggle Mic
toggle_mic() {
    if [ "$(pamixer --default-source --get-mute)" == "false" ]; then
        pamixer --default-source -m && notify-send -h string:x-canonical-private-synchronous:sys-notify -u low -i "$iDIR/microphone-mute.png" "Microphone muted"
    elif [ "$(pamixer --default-source --get-mute)" == "true" ]; then
        pamixer -u --default-source u && notify-send -h string:x-canonical-private-synchronous:sys-notify -u low -i "$iDIR/microphone.png" "Microphone unmuted"
    fi
}

# Get icons
get_mic_icon() {
    get_mic_volume
    if [[ "$MICVOLUME" -eq "0" ]]; then
        icon="$iDIR/microphone.png"
    elif [[ ("$MICVOLUME" -ge "0") && ("$MICVOLUME" -le "30") ]]; then
        icon="$iDIR/microphone.png"
    elif [[ ("$MICVOLUME" -ge "30") && ("$MICVOLUME" -le "60") ]]; then
        icon="$iDIR/microphone.png"
    elif [[ ("$MICVOLUME" -ge "60") && ("$MICVOLUME" -le "100") ]]; then
        icon="$iDIR/microphone.png"
    fi
}

# Notify
notify_mic_user() {
    notify-send -h string:x-canonical-private-synchronous:sys-notify -u low -i "$icon" "Microphone level : $MICVOLUME %"
}

# Increase MIC Volume
inc_mic_volume() {
    pamixer --default-source -i 5 && get_mic_icon && notify_mic_user
}

# Decrease MIC Volume
dec_mic_volume() {
    pamixer --default-source -d 5 && get_mic_icon && notify_mic_user
}

# Execute accordingly
if [[ "$1" == "--get" ]]; then
    get_volume
    echo "$VOLUME%"
elif [[ "$1" == "--inc" ]]; then
    inc_volume
elif [[ "$1" == "--dec" ]]; then
    dec_volume
elif [[ "$1" == "--toggle" ]]; then
    toggle_mute
elif [[ "$1" == "--get-mic" ]]; then
    get_mic_volume
    echo "$MICVOLUME%"
elif [[ "$1" == "--inc-mic" ]]; then
    inc_mic_volume
elif [[ "$1" == "--dec-mic" ]]; then
    dec_mic_volume
elif [[ "$1" == "--toggle-mic" ]]; then
    toggle_mic
else
    get_volume
    get_mic_volume
    echo "VOL: $VOLUME% | MIC: $MICVOLUME%"
fi
