#!/usr/bin/env bash

iDIR="$HOME/.config/waybar/icons"

# Get brightness percentage
get_percentage() {
    max="$(brightnessctl m)"
    cur="$(brightnessctl g)"
    PERCENTAGE=$((cur * 100 / max))
}

# Get icons
get_icon() {
    get_percentage
    if [[ ("$PERCENTAGE" -ge "0") && ("$PERCENTAGE" -le "20") ]]; then
        icon="$iDIR/brightness-20.png"
    elif [[ ("$PERCENTAGE" -ge "20") && ("$PERCENTAGE" -le "40") ]]; then
        icon="$iDIR/brightness-40.png"
    elif [[ ("$PERCENTAGE" -ge "40") && ("$PERCENTAGE" -le "60") ]]; then
        icon="$iDIR/brightness-60.png"
    elif [[ ("$PERCENTAGE" -ge "60") && ("$PERCENTAGE" -le "80") ]]; then
        icon="$iDIR/brightness-80.png"
    elif [[ ("$PERCENTAGE" -ge "80") && ("$PERCENTAGE" -le "100") ]]; then
        icon="$iDIR/brightness-100.png"
    fi
}

# Notify
notify_user() {
    notify-send -h string:x-canonical-private-synchronous:sys-notify -u low -i "$icon" "Brightness : $PERCENTAGE %"
}

# Increase brightness
inc_backlight() {
    brightnessctl set 10%+ && get_icon && notify_user
}

# Decrease brightness
dec_backlight() {
    brightnessctl set 10%- && get_icon && notify_user
}

# Execute accordingly
if [[ "$1" == "--get" ]]; then
    get_percentage
    echo "$PERCENTAGE%"
elif [[ "$1" == "--inc" ]]; then
    inc_backlight
elif [[ "$1" == "--dec" ]]; then
    dec_backlight
else
    get_percentage
    echo "$PERCENTAGE%"
fi
