#!/usr/bin/env bash

# If the operating system is not Arch Linux, exit the script successfully
if [ ! -f /etc/arch-release ]; then
    exit 0
fi

iDIR="$HOME/.config/waybar/icons"

notify_user() {
    notify-send -h string:x-canonical-private-synchronous:sys-notify -u normal -i "$iDIR/video.png" "Screen record saved."
}

create_video_dir() {
    if ! [ -d "~/Videos" ]; then
        mkdir -p ~/Videos
    fi
}

stop() {
    killall wf-recorder
    sleep 1
    pkill -RTMIN+2 waybar
    notify_user
}

ACTIVEMONITOR=$(hyprctl activeworkspace | grep "on monitor" | awk '{print $7}' | cut -d':' -f1 | head -1)
PCAUDIO=$(pactl list sources | grep Name | grep output | awk '{print $2}' | head -1)
DATENOW=$(date +'%F-%H-%M-%S')

if [ "$1" = "screen" ] || [ "$1" = "" ]; then
    if [ "$(pgrep wf-recorder)" = "" ]; then
        create_video_dir
        wf-recorder -o $ACTIVEMONITOR --audio=$PCAUDIO -f $HOME/Videos/screenrecord-$DATENOW.mp4 &>/dev/null &
    else
        stop
    fi
fi

if [ "$1" = "partial" ]; then
    if [ "$(pgrep wf-recorder)" = "" ]; then
        create_video_dir
        wf-recorder -g "$(slurp)" -o $ACTIVEMONITOR --audio=$PCAUDIO -f $HOME/Videos/screenrecord-$DATENOW.mp4 &>/dev/null &
    else
        stop
    fi
fi

if [ "$1" = "stop" ]; then
    stop
fi

