#!/usr/bin/env bash

# Original script by @speltriao on GitHub
# https://github.com/speltriao/Pacman-Update-for-GNOME-Shell

# If the operating system is not Arch Linux, exit the script successfully
if [ ! -f /etc/arch-release ]; then
    exit 0
fi

# If the parameter is "update", update all services
if [ "$1" = "update" ]; then
    kitty --title update-sys sh -c 'yay -Syu'
fi

# If there aren't any parameters, return the total number of updates
if [ "$1" = "" ]; then
    # Calculate updates for each service
    AUR=$(yay -Qua | wc -l)
    OFFICIAL=$(checkupdates | wc -l)

    # Calculate total number of updates
    COUNT=$((OFFICIAL+AUR))
    # If there are updates, the script will output the following:   Updates
    # If there are no updates, the script will output nothing.

    if [[ "$COUNT" = "0" ]]
    then
        echo "{\"text\": \"\"}"
    else
        echo "{\"text\": \"  $COUNT\", \"tooltip\": \"Oficial: $OFFICIAL | AUR: $AUR\"}"
    fi
    exit 0
fi
