#!/bin/bash

path=""

for entry in ~/.config/hypr/background/*
do
    if [[ $(file -b $entry) =~ PNG|JPEG ]]; then
        path="$entry"
        break
    fi
done

if [ "$path" != "" ]; then
    wal -nsteq -i $path
    cp -f $path  /usr/share/sddm/themes/sdt/wallpaper.jpg
    nohup swaybg -i $path &>/dev/null &
    sleep 1
    killall -SIGUSR2 waybar
    swaync-client -rs
fi

