#!/bin/bash

path=""

for entry in ~/.config/hypr/background/*
do
    if [[ $(file -b $entry) =~ PNG|JPEG ]]; then
        path="$entry"
        break
    fi
done

if [ "$path" != "" ]; then
    cp -f $path  /usr/share/sddm/themes/sdt/wallpaper.jpg
    nohup swaybg -i $path &>/dev/null &
fi

