"$schema" = 'https://starship.rs/config-schema.json'

format = """
[█](white)\
$os\
$username\
[](bg:black fg:white)\
$directory\
[](bg:bright-black fg:black)\
$git_branch\
$git_status\
[](bg:bright-white fg:bright-black)\
$bun\
$c\
$cpp\
$dart\
$dotnet\
$golang\
$haskell\
$java\
$kotlin\
$lua\
$nodejs\
$php\
$python\
$ruby\
$rust\
$zig\
[](fg:bright-white)\
$line_break$character"""

[os]
disabled = false
style = "bg:white fg:black"

[os.symbols]
Windows = "󰍲 "
Ubuntu = "󰕈 "
SUSE = " "
Raspbian = "󰐿 "
Mint = "󰣭 "
Macos = "󰀵"
Manjaro = " "
Linux = "󰌽 "
Gentoo = "󰣨 "
Fedora = "󰣛 "
Alpine = " "
Amazon = " "
Android = " "
Arch = "󰣇 "
Artix = "󰣇 "
CentOS = " "
Debian = "󰣚"
Redhat = "󱄛 "
RedHatEnterprise = "󱄛 "

[username]
show_always = false
style_user = "bg:white fg:black"
style_root = "bg:white fg:black"
format = '[ $user ]($style)'

[directory]
style = "bg:black fg:white"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"
read_only = ""

[git_branch]
symbol = ""
style = "bg:bright-black fg:bright-white"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:bright-black fg:bright-white"
format = '[($all_status$ahead_behind )]($style)'

[bun]
symbol = ""
style = "bg:bright-white fg:black"
format = '[ $symbol( $version) ]($style)'

[c]
symbol = ""
style = "bg:bright-white fg:black"
format = '[ $symbol( $version(-$name))]($style)'

[cpp]
symbol = "󰙲"
style = "bg:bright-white fg:black"
format = '[ $symbol( $version(-$name))]($style)'

[dart]
symbol = ""
style = "bg:bright-white fg:black"
format = '[ $symbol( $version) ]($style)'

[dotnet]
symbol = "󰪮"
style = "bg:bright-white fg:black"
format = '[ $symbol( $version) ]($style)'

[golang]
symbol = "󰟓"
style = "bg:bright-white fg:black"
format = '[ $symbol( $version) ]($style)'

[haskell]
symbol = ""
style = "bg:bright-white fg:black"
format = '[ $symbol( $version) ]($style)'

[java]
symbol = ""
style = "bg:bright-white fg:black"
format = '[ $symbol( $version) ]($style)'

[kotlin]
symbol = ""
style = "bg:bright-white fg:black"
format = '[ $symbol( $version) ]($style)'

[lua]
symbol = ""
style = "bg:bright-white fg:black"
format = '[ $symbol( $version) ]($style)'

[nodejs]
symbol = ""
style = "bg:bright-white fg:black"
format = '[ $symbol( $version) ]($style)'

[php]
symbol = ""
style = "bg:bright-white fg:black"
format = '[ $symbol( $version) ]($style)'

[python]
symbol = ""
style = "bg:bright-white fg:black"
format = '[ $symbol( $version) ]($style)'

[ruby]
symbol = ""
style = "bg:bright-white fg:black"
format = '[ $symbol( $version) ]($style)'

[rust]
symbol = ""
style = "bg:bright-white fg:black"
format = '[ $symbol( $version) ]($style)'

[zig]
symbol = ""
style = "bg:bright-white fg:black"
format = '[ $symbol( $version) ]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[](bold fg:green)'
error_symbol = '[](bold fg:red)'
vimcmd_symbol = '[](bold fg:green)'
vimcmd_replace_one_symbol = '[](bold fg:purple)'
vimcmd_replace_symbol = '[](bold fg:purple)'
vimcmd_visual_symbol = '[](bold fg:yellow)'
