import = [
    "tokyonight.toml"
]

[env]
TERM = "xterm-256color"

[font]
    normal = { family = "SauceCodePro Nerd Font" }
    size = 13

[window]
    decorations = "None"
    opacity = 0.85
    startup_mode = "Maximized"

[mouse]
    hide_when_typing = true
